
[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[colors.bright]
black = "#666666"
blue = "#576fe6"
cyan = "#72c1db"
green = "#55bb55"
magenta = "#e890b5"
red = "#ee6666"
white = "#eaeaea"
yellow = "#eeee66"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#1c1f2b"
blue = "#3c53b5"
cyan = "#4aa9cf"
green = "#33aa44"
magenta = "#f255a6"
red = "#cc4444"
white = "#c5c8c6"
yellow = "#eedd11"

[colors.primary]
background = "#1c1f2b"
bright_foreground = "#eaeaea"
dim_foreground = "#828482"
foreground = "#c5c8c6"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[font]
size = 14.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
opacity = 0.8
title = "Alacritty"

[window.padding]
x = 15
y = 10
